config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :heros, only: %i[index new create show] do
    resources :bookings, only: %i[create]
  end

  get 'dashboard', to: 'pages#dashboard'

  resources :bookings, only: [] do
    member do
      patch :accept
      patch :refuse
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :hero

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/hero.rb
class Hero < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo

  validates :power, presence: true
  validates :description, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name_and_power,
    against: [:name, :power],

    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :heros
  has_many :bookings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @hero = Hero.find(params[:hero_id])
    @booking = Booking.new(booking_params)
    @booking.hero = @hero
    @booking.user = current_user
    @booking.status = "pending"
    if @booking.save
      redirect_to dashboard_path
    else
      render "heros/show", status: :unprocessable_entity
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update(status: "accepted")
    flash[:notice] = "The booking has been approved"
    redirect_to dashboard_path
  end

  def refuse
    @booking = Booking.find(params[:id])
    @booking.update(status: "rejected")
    flash[:notice] = "The booking has been rejected"
    redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/heros_controller.rb
class HerosController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @heros = Hero.all
    @heros = @heros.search_by_name_and_power(params[:query]) if params[:query].present?
    # @heros = @heros.where(name: params[:name]) if params[:name].present?
    # @heros = @heros.where(power: params[:power]) if params[:power].present?
  end

  def show
    @hero = Hero.find(params[:id])
    @booking = Booking.new
  end

  def new
    @hero = Hero.new
  end

  def create
    @hero = Hero.new(hero_params)
    @hero.user = current_user
    @hero.photo.attach(params[:hero][:photo])
    if @hero.save
      redirect_to dashboard_path, notice: "the super-hero was created successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

private

  def hero_params
    params.require(:hero).permit(:name, :power, :description, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @bookings = Booking.where(user: current_user, status: "pending")
    @heros = Hero.where(user: current_user)
    @bookings_owner = []
    @heros.each do |hero|
      if !Booking.where(hero: hero).empty?
        @bookings_owner << Booking.where(hero: hero)
      end
    end
    @bookings_owner.flatten!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/heros/index.html.erb
<div class="container-lg" >


      <h1>Heroes</h1>

      <%= form_with url: heros_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Search your hero or your power" %>
        <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
      <% end %>


    <div class="row mt-4">
      <% @heros.each do |hero| %>
        <div class="col-md-4 mb-4"> <!-- 3 cartes par ligne sur desktop -->
          <%= link_to hero_path(hero), class: "card-link" do %> <!-- Pour que la card soit cliquable  -->
            <div class="card shadow-sm card-link">

              <%= cl_image_tag(hero.photo.key, class: "card-img-top", alt: hero.name, crop: :fill) %>
                <div class="card-body">
                  <h5 class="card-title"><%= hero.name %></h5>
                  <p class="card-text"><strong><i class="fa-solid fa-bolt"></i></strong> <%= hero.power %></p>
                </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

app/views/heros/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
    <h1>Create a new heroe</h1>
      <div>
          <%= simple_form_for @hero do |f|  %>
          <%= f.input :name  %>
          <%= f.input :power  %>
          <%= f.input :description  %>
          <%= f.input :photo, as: :file  %>
          <%= f.submit %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/heros/show.html.erb
<div class="container-lg">
  <div class="row align-items-start">
    <div class="col-md-6">
      <div class="card shadow-sm mt-5">
        <%= cl_image_tag(@hero.photo.key, class: "hero-image", alt: @hero.name) %>
        <div class="card-body">
          <h5 class="card-title"><%= @hero.name %></h5>
          <p class="card-text"><strong><i class="fa-solid fa-bolt"></i></strong> <%= @hero.power %></p>
          <p class="card-text">Description: <%= @hero.description %></p>
        </div>
      </div>
    </div>


    <div class="col-md-6 d-flex flex-column justify-content-start align-items-center">
      <div data-controller="toggle" class="w-50 ms-auto">
        <button class="btn btn-primary mt-5" data-action="click->toggle#fire">Do you want to rent?</button>

        <div data-toggle-target="togglableElement" class="d-none">
          <%= simple_form_for [@hero, @booking] do |f| %>
            <%= f.input :start_date, as: :string,
                  input_html: { class: "text-white", data: { controller: "datepicker" } } %>
            <%= f.input :end_date, as: :string,
                  input_html: { class: "text-white", data: { controller: "datepicker" } } %>
            <%= f.button :submit, "Book a SuperHero", class: "btn btn-primary mt-2" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuperHero</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <%= link_to root_path, class: "mask" do %>
        <i class="fa-solid fa-mask"></i>
      <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">

        <a class="nav-link" href="<%= dashboard_path %>">Dashboard</a>

          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= heros_path %>">Heroes</a>
          </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#"></a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
            </div>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>

    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="container-lg">
    <h1 class="py-2">  <i class="fa-solid fa-meteor"></i> Renter section </h1>
    <h2 class="py-2">My pending bookings</h2>
      <div class="row">
        <% @bookings.each do |booking| %>
          <div class="col-md-2 mb-3">
              <div class="medium-card shadow-sm" >
                <%= link_to cl_image_tag(booking.hero.photo.key, class: "medium-card-img px-0", alt: booking.hero.name), hero_path(booking.hero) %>
                <div class="medium-card-body">
                  <h5 class="medium-card-title m-0"><%= booking.hero.name %></h5>
                  <p class="medium-card-text m-0"><%= booking.start_date %></p>
                  <p class="medium-card-text m-0"><%= booking.status %> </p>
                </div>
              </div>
          </div>
        <% end %>
      </div>
  </div>

  <div class="mt-3 pt-3">
    <h1><i class="fa-solid fa-hand-spock"></i>Owner section</h1>
    <h2>My validations</h2>

    <% @bookings_owner.each do |booking| %>
      <div class= "pendinglist d-flex flex-row">
        <%= booking.hero.name %> |
          starting date on <%= booking.start_date %> |
          ending date on <%= booking.end_date %> |
        <%= booking.status %>
        <% if booking.status == "pending" %>
        <%= button_to "accept", accept_booking_path(booking), method: :patch, class:"btn btn-primary btn-sm" %>
        or <%= button_to "refuse", refuse_booking_path(booking), method: :patch, class:"btn btn-primary btn-sm" %>
      <% end %>
      </div>
    <% end %>

    <h2>My SuperHeroes</h2>

<div class="cards">
      <% @heros.each do |hero| %>
        <div class="card shadow-sm d-flex flex-row"><%= cl_image_tag(hero.photo.key, class: "mini_card hero-image", alt: hero.name) %>
        <div class="m-3 mt-5"> <h5 class="card-title"><%= hero.name %></h5>
        <p class="text-dark"><%= hero.power %> | <%= hero.description %></p>
        </div>
        </div>
    <% end %>

</div>
<button class="btn btn-primary mt-5"> <%= link_to "Create a SuperHeroe",  new_hero_path, class: "text-decoration-none text-white" %> </button>
</div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image:url(<%= asset_path('homepageimg.jpg') %>); height: 700px;">
  <div class="container">
    <h1><strong>CapeForRent</strong></h1>
    <p> Rent a cape, save your day !</p>
    <%= link_to "Discover all heroes !", heros_path, class: "btn btn-primary" %>
  </div>
</div>